using ClosedBurger.Application.Messaging;
namespace ClosedBurger.Application.Features.AppFeatures.MainRoleAndUserRLFeatures.Commands.RemoveByIdMainRoleAndUserRL;
public sealed record RemoveByIdMainRoleAndUserRLCommand(string Id) : ICommand<RemoveByIdMainRoleAndUserRLCommandResponse>;